services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\CountLinesCodeBundle\Command\:
        resource: '../../Command/*'

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
